workloadAsStatefulSet: true
strategyType: OnDelete

minecraftServer:
  eula: "TRUE"
  version: "LATEST"
  type: "VANILLA"
  serviceType: LoadBalancer

persistence:
  dataDir:
    enabled: true
    Size: 10Gi
